### ISSUE TITLE
Vortex Compiler

### ISSUE THREAD

**Issue by wonook** [snuspl/onyx#8]
## This issue is for keeping track of the subtasks

The `Vortex Compiler` is composed of three components: the `Frontend`, the `Optimizer`, and the `Backend`. The structure is similar to the [LLVM](http://www.aosabook.org/en/llvm.html) compiler structure.

We will create a `Vortex IR` from the given DAG of BEAM program through the `Frontend` and process and optimize it, to pass it on to the `Backend` which transforms the Vortex IR into an `ExecutionPlan` which will be received and processed by the `Vortex Runtime` (#9).

### Vortex IR
The main job of the `Vortex Compiler` is to label each of the vertices and edges of the DAG with specific attributes including:
#### Vertex:
- implemented as classes of:
  - SourceVertex
  - OperatorVertex
    - Transform
      - DoTransform
      - GroupByKeyTransform
      - WindowTransform
- with attributes:
  - Placement
    - e.g. Reserved/Transient
    - e.g. Storage/Compute
  - Parallelism
    - e.g. # of partitions
#### Edges:
- with attributes:
  - EdgeChannel (distinguishes intermediate data location)
    - Local Memory
    - TCP Pipe (push)
    - File (local disk)
    - Distributed Filesystem
  - Relation
    - ScatterGather (M2M)
    - OneToOne (O2O)
    - Broadcast (O2M)

### Vortex Labeling & Correctness Check
The placement/labeling algorithm/policy will be pluggable and will be decided by the user, customized for each of the usages and environments. While labeling each nodes and edges, it will also check if there are any anomalies in the DAG. Our previous implementation of transient-reserved-specified Vortex will use the algorithm shown in the paper. The specifications and the details of the policy are shown under the `compiler.optimizer.passes` package. Each pass receives a DAG and outputs another DAG, tagged with attributes.

### Vortex DAG Optimization
The `Compiler` can further optimize the DAG for it to be run efficiently on the `Runtime` layer, by adding/merging/removing operators, modifying edges, and tweaking system attributes. (like FlumeJava, etc.)
This would also be ideal to be done during the Runtime.

### Vortex Stage Generation
Then, the `Compiler Backend` splits the DAG into `Vortex Stages` (#73).

Details and the following sub-issues will be updated.

### Sub-issues:
- [x] Add more sub-issues
- [x] #12 Sink Node 
- [x] #25 Compiler interfaces
- [x] #76 new IR
- [x] #29 Configurable Optimizer
- [x] #21 Refactor Attributes class
- [ ] #13 Join Node
- [ ] #22 DAG Integrity check
- [ ] #14 Multi-Output Do node
- [x] #28 VortexBackend
- [ ] #30 Tang to parse user arguments
- [ ] #31 Interfaces for Runtime Optimization
- [ ] #56 More instantiation policies

- [ ] #36 Stream support
